import type { Metadata } from "next";
import "@/app/ui/globals.css";
import NavLinks from "./ui/dashboard/nav-links";

export const metadata: Metadata = {
  title: "NextJS Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex">
        {/* Sidebar */}
        <aside className="w-64 bg-gray-50 p-4 border-r sticky top-0 h-screen">
          <h1 className="text-xl font-bold mb-6">Dashboard</h1>
          <NavLinks />
        </aside>

        {/* Main Content */}
        <main className="flex-1 p-6 bg-gray-100 min-h-screen">{children}</main>
      </body>
    </html>
  );
}
